{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "import sys\n",
    "import os\n",
    "import datetime as dt\n",
    "import time\n",
    "import logging\n",
    "\n",
    "\n",
    "from _setup_routines import _init_logs, _setup_engine"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "collapsed": false,
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 980, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 830, in format\n",
      "    return fmt.format(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 570, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 539, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 383, in format\n",
      "    return self._fmt % record.__dict__\n",
      "ValueError: unsupported format character '\"' (0x22) at index 34\n",
      "Call stack:\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\runpy.py\", line 170, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\__main__.py\", line 3, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\traitlets\\config\\application.py\", line 596, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 442, in start\n",
      "    ioloop.IOLoop.instance().start()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\ioloop.py\", line 162, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\tornado\\ioloop.py\", line 883, in start\n",
      "    handler_func(fd_obj, events)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\tornado\\stack_context.py\", line 275, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 440, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 472, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 414, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\tornado\\stack_context.py\", line 275, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 276, in dispatcher\n",
      "    return self.dispatch_shell(stream, msg)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 228, in dispatch_shell\n",
      "    handler(stream, idents, msg)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 391, in execute_request\n",
      "    user_expressions, allow_stdin)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 199, in do_execute\n",
      "    shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2723, in run_cell\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2825, in run_ast_nodes\n",
      "    if self.run_code(code, result):\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2885, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-3627299e993b>\", line 1, in <module>\n",
      "    wc_log = _init_logs()\n",
      "  File \"C:\\Users\\Galen\\git\\w.c\\_setup_routines.py\", line 44, in _init_logs\n",
      "    log.debug(\"Starting in %s\" % STARTUP_PATH)\n",
      "Message: 'Starting in C:\\\\Users\\\\Galen\\\\git\\\\w.c'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 980, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 830, in format\n",
      "    return fmt.format(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 570, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 539, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 383, in format\n",
      "    return self._fmt % record.__dict__\n",
      "ValueError: unsupported format character '\"' (0x22) at index 34\n",
      "Call stack:\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\runpy.py\", line 170, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\__main__.py\", line 3, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\traitlets\\config\\application.py\", line 596, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 442, in start\n",
      "    ioloop.IOLoop.instance().start()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\ioloop.py\", line 162, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\tornado\\ioloop.py\", line 883, in start\n",
      "    handler_func(fd_obj, events)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\tornado\\stack_context.py\", line 275, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 440, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 472, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 414, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\tornado\\stack_context.py\", line 275, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 276, in dispatcher\n",
      "    return self.dispatch_shell(stream, msg)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 228, in dispatch_shell\n",
      "    handler(stream, idents, msg)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 391, in execute_request\n",
      "    user_expressions, allow_stdin)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 199, in do_execute\n",
      "    shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2723, in run_cell\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2825, in run_ast_nodes\n",
      "    if self.run_code(code, result):\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2885, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-3627299e993b>\", line 1, in <module>\n",
      "    wc_log = _init_logs()\n",
      "  File \"C:\\Users\\Galen\\git\\w.c\\_setup_routines.py\", line 45, in _init_logs\n",
      "    log.debug(\"Versions:\")\n",
      "Message: 'Versions:'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 980, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 830, in format\n",
      "    return fmt.format(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 570, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 539, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 383, in format\n",
      "    return self._fmt % record.__dict__\n",
      "ValueError: unsupported format character '\"' (0x22) at index 34\n",
      "Call stack:\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\runpy.py\", line 170, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\__main__.py\", line 3, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\traitlets\\config\\application.py\", line 596, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 442, in start\n",
      "    ioloop.IOLoop.instance().start()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\ioloop.py\", line 162, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\tornado\\ioloop.py\", line 883, in start\n",
      "    handler_func(fd_obj, events)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\tornado\\stack_context.py\", line 275, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 440, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 472, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 414, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\tornado\\stack_context.py\", line 275, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 276, in dispatcher\n",
      "    return self.dispatch_shell(stream, msg)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 228, in dispatch_shell\n",
      "    handler(stream, idents, msg)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 391, in execute_request\n",
      "    user_expressions, allow_stdin)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 199, in do_execute\n",
      "    shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2723, in run_cell\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2825, in run_ast_nodes\n",
      "    if self.run_code(code, result):\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2885, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-3627299e993b>\", line 1, in <module>\n",
      "    wc_log = _init_logs()\n",
      "  File \"C:\\Users\\Galen\\git\\w.c\\_setup_routines.py\", line 46, in _init_logs\n",
      "    log.debug(\"  slqalchemy: %s\" % sa.__version__)\n",
      "Message: '  slqalchemy: 1.0.13'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 980, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 830, in format\n",
      "    return fmt.format(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 570, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 539, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 383, in format\n",
      "    return self._fmt % record.__dict__\n",
      "ValueError: unsupported format character '\"' (0x22) at index 34\n",
      "Call stack:\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\runpy.py\", line 170, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\__main__.py\", line 3, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\traitlets\\config\\application.py\", line 596, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 442, in start\n",
      "    ioloop.IOLoop.instance().start()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\ioloop.py\", line 162, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\tornado\\ioloop.py\", line 883, in start\n",
      "    handler_func(fd_obj, events)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\tornado\\stack_context.py\", line 275, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 440, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 472, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 414, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\tornado\\stack_context.py\", line 275, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 276, in dispatcher\n",
      "    return self.dispatch_shell(stream, msg)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 228, in dispatch_shell\n",
      "    handler(stream, idents, msg)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 391, in execute_request\n",
      "    user_expressions, allow_stdin)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 199, in do_execute\n",
      "    shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2723, in run_cell\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2825, in run_ast_nodes\n",
      "    if self.run_code(code, result):\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2885, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-3627299e993b>\", line 1, in <module>\n",
      "    wc_log = _init_logs()\n",
      "  File \"C:\\Users\\Galen\\git\\w.c\\_setup_routines.py\", line 47, in _init_logs\n",
      "    log.debug(\"     sqlite3: %s\" % db.version)\n",
      "Message: '     sqlite3: 2.6.0'\n",
      "Arguments: ()\n"
     ]
    }
   ],
   "source": [
    "wc_log = _init_logs()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 980, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 830, in format\n",
      "    return fmt.format(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 570, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 539, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 383, in format\n",
      "    return self._fmt % record.__dict__\n",
      "ValueError: unsupported format character '\"' (0x22) at index 34\n",
      "Call stack:\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\runpy.py\", line 170, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\__main__.py\", line 3, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\traitlets\\config\\application.py\", line 596, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 442, in start\n",
      "    ioloop.IOLoop.instance().start()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\ioloop.py\", line 162, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\tornado\\ioloop.py\", line 883, in start\n",
      "    handler_func(fd_obj, events)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\tornado\\stack_context.py\", line 275, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 440, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 472, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 414, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\tornado\\stack_context.py\", line 275, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 276, in dispatcher\n",
      "    return self.dispatch_shell(stream, msg)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 228, in dispatch_shell\n",
      "    handler(stream, idents, msg)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 391, in execute_request\n",
      "    user_expressions, allow_stdin)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 199, in do_execute\n",
      "    shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2723, in run_cell\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2825, in run_ast_nodes\n",
      "    if self.run_code(code, result):\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2885, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-3-a63631bd4e0c>\", line 1, in <module>\n",
      "    db_engine = _setup_engine()\n",
      "  File \"C:\\Users\\Galen\\git\\w.c\\_setup_routines.py\", line 64, in _setup_engine\n",
      "    log.debug(\" db_dir:: %s\" % db_dir)\n",
      "Message: ' db_dir:: C:\\\\Users\\\\Galen\\\\git\\\\db'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 980, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 830, in format\n",
      "    return fmt.format(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 570, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 539, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\logging\\__init__.py\", line 383, in format\n",
      "    return self._fmt % record.__dict__\n",
      "ValueError: unsupported format character '\"' (0x22) at index 34\n",
      "Call stack:\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\runpy.py\", line 170, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\__main__.py\", line 3, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\traitlets\\config\\application.py\", line 596, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 442, in start\n",
      "    ioloop.IOLoop.instance().start()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\ioloop.py\", line 162, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\tornado\\ioloop.py\", line 883, in start\n",
      "    handler_func(fd_obj, events)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\tornado\\stack_context.py\", line 275, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 440, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 472, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 414, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\tornado\\stack_context.py\", line 275, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 276, in dispatcher\n",
      "    return self.dispatch_shell(stream, msg)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 228, in dispatch_shell\n",
      "    handler(stream, idents, msg)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 391, in execute_request\n",
      "    user_expressions, allow_stdin)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 199, in do_execute\n",
      "    shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2723, in run_cell\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2825, in run_ast_nodes\n",
      "    if self.run_code(code, result):\n",
      "  File \"C:\\Users\\Galen\\Anaconda2\\envs\\py3k\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2885, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-3-a63631bd4e0c>\", line 1, in <module>\n",
      "    db_engine = _setup_engine()\n",
      "  File \"C:\\Users\\Galen\\git\\w.c\\_setup_routines.py\", line 65, in _setup_engine\n",
      "    log.debug(\"db_name:: %s\" % db_name)\n",
      "Message: 'db_name:: C:\\\\Users\\\\Galen\\\\git\\\\db\\\\work_cards.db'\n",
      "Arguments: ()\n"
     ]
    }
   ],
   "source": [
    "db_engine = _setup_engine()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (py3k)",
   "language": "python",
   "name": "py3k"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
